export type ValidSkills =
  // --- Languages ---
  | "Javascript"
  | "Typescript"
  | "Python"
  | "Java"
  | "C++"
  | "C#"
  | "Ruby"
  | "Go"
  | "Golang"
  | "Rust"
  | "PHP"
  | "Dart"
  | "Swift"
  | "Kotlin"
  | "SQL"
  | "NoSQL"

  // --- Frontend & UI ---
  | "React"
  | "Next.js"
  | "Vue.js"
  | "Nuxt.js"
  | "Angular"
  | "Svelte"
  | "Solid.js"
  | "HTML 5"
  | "CSS 3"
  | "Sass"
  | "Less"
  | "Tailwind CSS"
  | "Bootstrap"
  | "Material UI"
  | "Chakra UI"
  | "Radix UI"
  | "shadcn/ui"
  | "Redux"
  | "Framer Motion"
  | "Three.js"
  | "WebGL"

  // --- Backend & APIs ---
  | "Node.js"
  | "express.js"
  | "Nest.js"
  | "Django"
  | "FastAPI"
  | "Flask"
  | "Spring Boot"
  | "Laravel"
  | "Ruby on Rails"
  | ".NET"
  | "GraphQL"
  | "REST API"
  | "tRPC"
  | "Apollo"
  | "Google Auth"
  | "Socket.io"
  | "WebSockets"
  | "gRPC"
  | "Serverless"
  | "AWS Lambda"
  | "Azure Functions"
  | "Google Cloud Functions"
  | "Firebase Functions"
  | "Supabase Functions"
  | "Edge Functions"
  | "WebAssembly"
  | "Scripting"
  | "Bash"
  | "Automation"
  | "Cron Jobs"
  | "rsync"
  | "Shell Scripting"

  // --- Mobile Development ---
  | "React Native"
  | "Flutter"

  // --- Database & ORM ---
  | "MongoDB"
  | "MySQL"
  | "PostgreSQL"
  | "Postgresql"
  | "SQLite"
  | "Redis"
  | "Oracle"
  | "DynamoDB"
  | "Cassandra"
  | "Prisma"
  | "TypeORM"
  | "Mongoose"
  | "Drizzle ORM"

  // --- Cloud, DevOps, SysAdmin & Security ---
  | "AWS"
  | "Google Cloud"
  | "Azure"
  | "Cloudflare"
  | "Firebase"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Heroku"
  | "Docker"
  | "Kubernetes"
  | "Linux"
  | "RHEL"
  | "Server Management"
  | "Network Security"
  | "Security Management"
  | "Git"
  | "CI/CD"
  | "GitHub Actions"
  | "GitLab CI"
  | "Jenkins"
  | "Terraform"

  // --- AI, ML & Data Engineering ---
  | "TensorFlow"
  | "PyTorch"
  | "Scikit-Learn"
  | "Pandas"
  | "NumPy"
  | "OpenCV"
  | "Databricks"

  // --- Tools & Testing ---
  | "Figma"
  | "Webpack"
  | "Vite"
  | "Jest"
  | "Cypress"
  | "Playwright"
  | "Vitest"
  | "Storybook"

  // --- Architecture ---
  | "Microservices";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Game Development"
  | "3D Modeling"
  | "Data Science"
  | "Machine Learning"
  | "Artificial Intelligence"
  | "DevOps"
  | "Cloud Computing"
  | "Cybersecurity"
  | "Blockchain"
  | "QA/Testing"
  | "System Architecture";

export type ValidExpType =
  | "Personal"
  | "Professional"
  | "Freelance"
  | "Open Source"
  | "Internship"
  | "Academic"
  | "Volunteer";

export type ValidPages =
  | "home"
  | "about"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "repositories"
  | "resume"
  | "blogs"
  | "services"
  | "testimonials"
  | "portfolio"
  | "guestbook"
  | "snippets"
  | "uses";

export type ValidProjectStatus =
  | "Done"
  | "In Progress"
  | "Maintained"
  | "Planned";