export const siteConfig = {
  name: "Sultan Arif - Cyber Security Student | Full Stack Developer | RHCSA",
  authorName: "Sultan Arif",
  username: "RMSULTAN256",
  description:
    "Sultan Arif - Cyber Security Student | Full Stack Developer | RHCSA. Welcome to my portfolio website.",
  url: "https://sultanarif.xyz",
  links: {
    twitter: "https://x.com/sultanarif",
    github: "https://github.com/RMSULTAN256",
    templateRepo: "https://github.com/RMSULTAN256/myproton",
  },
  ogImage:
    "https://res.cloudinary.com/dvt5vkfwz/image/upload/v1767384721/sultanarif_portfolio_og_image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Sultan Arif",
    "Cyber Security Student",
    "Full Stack Developer",
    "RHCSA",
    "Red Hat Certified System Administrator",
    "Software Engineer",
    "Full Stack Developer",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Linux Administrator",
    "Network Security",
  ],
};
